# build and deploy enabled on this fork 2022-05-15
name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2

    #   - name: Install and Build
    #     run: |
    #       npm ci
    #       npm run build

    #   - name: Deploy
    #     uses: JamesIves/github-pages-deploy-action@4.0.0
    #     with:
    #       branch: gh-pages # The branch the action should deploy to.
    #       folder: public # The folder the action should deploy.

  publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rvlq/coursepage:latest

### from: https://github.com/AkhileshNS/heroku-deploy ###
# name: Deploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "docker-course-page-test" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true

